version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: springbootangular-postgres-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=springbootangular-*zaDHu*tCH8y
      - APP_DB_USER=dbo_user
      - APP_DB_PASS=K95^eHcSRw8w
      - APP_DB_NAME=spring_boot_angular
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432