spring:
  profiles:
    active: development
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_debug
    username: dbo_user
    password: K95^eHcSRw8w
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
server:
  port: 8080
  servlet:
    context-path: /learn-debug